name: 'Initial Setup'

on: [ create ]

permissions:
  issues: write
  contents: read

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create setup-app
          gh label create link-azure
          gh label create create-environment

          owner=$(echo ${{ github.repository }} | cut -d '/' -f 1)

          cat .github/workflows/templates/init.tpl \
          | sed "s|@@REPO@@|${{ github.server_url }}/${{ github.repository }}|g" \
          | sed "s|@@OWNER@@|${owner}|g" \
          | sed "s|@@SERVER_URL@@|${{ github.server_url }}|g" \
          | gh issue create -t "Create GitHub App" -F - -l "setup-app"
