on:
  push:
    branches:
      - main
    paths:
      - 'WORKSPACES/LIBRARY/*'

jobs:
  update-config:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xpiritbv/azure-sap-automation:github-workflow

    steps:
      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "sap-automation-deployer@noreply.github.com"
          .github/workflows/scripts/update-workflow-on-workspaces-changes.sh
